module Evergreen.Migrate.V12 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V12.Auth.Common
import Evergreen.V12.Logger
import Evergreen.V12.OAuth
import Evergreen.V12.OAuth.AuthorizationCode
import Evergreen.V12.Types
import Evergreen.V4.Auth.Common
import Evergreen.V4.Logger
import Evergreen.V4.OAuth
import Evergreen.V4.OAuth.AuthorizationCode
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V4.Types.FrontendModel -> ModelMigration Evergreen.V12.Types.FrontendModel Evergreen.V12.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V4.Types.BackendModel -> ModelMigration Evergreen.V12.Types.BackendModel Evergreen.V12.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V4.Types.FrontendMsg -> MsgMigration Evergreen.V12.Types.FrontendMsg Evergreen.V12.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V4.Types.ToBackend -> MsgMigration Evergreen.V12.Types.ToBackend Evergreen.V12.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V4.Types.BackendMsg -> MsgMigration Evergreen.V12.Types.BackendMsg Evergreen.V12.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V4.Types.ToFrontend -> MsgMigration Evergreen.V12.Types.ToFrontend Evergreen.V12.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V4.Types.FrontendModel -> Evergreen.V12.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentRoute = old.currentRoute |> migrate_Types_Route
    , adminPage = old.adminPage |> migrate_Types_AdminPageModel
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    , login = old.login |> migrate_Types_LoginState
    , currentUser = old.currentUser
    , pendingAuth = old.pendingAuth
    , preferences = old.preferences |> migrate_Types_Preferences
    , emailPasswordForm = old.emailPasswordForm |> migrate_Types_EmailPasswordFormModel
    , profileDropdownOpen = old.profileDropdownOpen
    , loginModalOpen = old.loginModalOpen
    , clients = old.clients
    , selectedClientId = old.selectedClientId
    , destinationUrl = old.destinationUrl
    , utmSource = old.utmSource
    , utmMedium = old.utmMedium
    , utmCampaign = old.utmCampaign
    , utmTerm = old.utmTerm
    , utmContent = old.utmContent
    , shortenResults = []
    , isShortening = old.isShortening
    , newClientName = old.newClientName
    , newClientApiKey = old.newClientApiKey
    , clientFormError = old.clientFormError
    , showClientManager = old.showClientManager
    , newSourceInput = old.newSourceInput
    , newTagInput = old.newTagInput
    , editingClientId = old.editingClientId
    , selectedSources = old.selectedSources
    , selectedTags = old.selectedTags
    , linksForDashboard = old.linksForDashboard
    , dashboardSortColumn = old.dashboardSortColumn |> migrate_Types_DashboardColumn
    , dashboardSortDirection = old.dashboardSortDirection |> migrate_Types_SortDirection
    , dashboardFilters = old.dashboardFilters
    }


migrate_Auth_Common_Error : Evergreen.V4.Auth.Common.Error -> Evergreen.V12.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V4.Auth.Common.ErrStateMismatch ->
            Evergreen.V12.Auth.Common.ErrStateMismatch

        Evergreen.V4.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V12.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V4.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V12.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V4.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V12.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V4.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V12.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V4.Auth.Common.ErrAuthString p0 ->
            Evergreen.V12.Auth.Common.ErrAuthString p0


migrate_Auth_Common_Flow : Evergreen.V4.Auth.Common.Flow -> Evergreen.V12.Auth.Common.Flow
migrate_Auth_Common_Flow old =
    case old of
        Evergreen.V4.Auth.Common.Idle ->
            Evergreen.V12.Auth.Common.Idle

        Evergreen.V4.Auth.Common.Requested p0 ->
            Evergreen.V12.Auth.Common.Requested p0

        Evergreen.V4.Auth.Common.Pending ->
            Evergreen.V12.Auth.Common.Pending

        Evergreen.V4.Auth.Common.Authorized p0 p1 ->
            Evergreen.V12.Auth.Common.Authorized p0 p1

        Evergreen.V4.Auth.Common.Authenticated p0 ->
            Evergreen.V12.Auth.Common.Authenticated (p0 |> migrate_OAuth_Token)

        Evergreen.V4.Auth.Common.Done p0 ->
            Evergreen.V12.Auth.Common.Done (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V4.Auth.Common.Errored p0 ->
            Evergreen.V12.Auth.Common.Errored (p0 |> migrate_Auth_Common_Error)


migrate_Auth_Common_UserInfo : Evergreen.V4.Auth.Common.UserInfo -> Evergreen.V12.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Logger_LogEntry : Evergreen.V4.Logger.LogEntry -> Evergreen.V12.Logger.LogEntry
migrate_Logger_LogEntry old =
    { index = old.index
    , timestamp = old.timestamp
    , level = old.level |> migrate_Logger_LogLevel
    , message = old.message
    }


migrate_Logger_LogLevel : Evergreen.V4.Logger.LogLevel -> Evergreen.V12.Logger.LogLevel
migrate_Logger_LogLevel old =
    case old of
        Evergreen.V4.Logger.Debug ->
            Evergreen.V12.Logger.Debug

        Evergreen.V4.Logger.Info ->
            Evergreen.V12.Logger.Info

        Evergreen.V4.Logger.Warn ->
            Evergreen.V12.Logger.Warn

        Evergreen.V4.Logger.Error ->
            Evergreen.V12.Logger.Error


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V4.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V12.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V4.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V12.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V4.OAuth.ErrorCode -> Evergreen.V12.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V4.OAuth.InvalidRequest ->
            Evergreen.V12.OAuth.InvalidRequest

        Evergreen.V4.OAuth.UnauthorizedClient ->
            Evergreen.V12.OAuth.UnauthorizedClient

        Evergreen.V4.OAuth.AccessDenied ->
            Evergreen.V12.OAuth.AccessDenied

        Evergreen.V4.OAuth.UnsupportedResponseType ->
            Evergreen.V12.OAuth.UnsupportedResponseType

        Evergreen.V4.OAuth.InvalidScope ->
            Evergreen.V12.OAuth.InvalidScope

        Evergreen.V4.OAuth.ServerError ->
            Evergreen.V12.OAuth.ServerError

        Evergreen.V4.OAuth.TemporarilyUnavailable ->
            Evergreen.V12.OAuth.TemporarilyUnavailable

        Evergreen.V4.OAuth.Custom p0 ->
            Evergreen.V12.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V4.OAuth.Token -> Evergreen.V12.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V4.OAuth.Bearer p0 ->
            Evergreen.V12.OAuth.Bearer p0


migrate_Types_AdminLogsUrlParams : Evergreen.V4.Types.AdminLogsUrlParams -> Evergreen.V12.Types.AdminLogsUrlParams
migrate_Types_AdminLogsUrlParams old =
    old


migrate_Types_AdminPageModel : Evergreen.V4.Types.AdminPageModel -> Evergreen.V12.Types.AdminPageModel
migrate_Types_AdminPageModel old =
    { logs = old.logs |> List.map migrate_Logger_LogEntry
    , isAuthenticated = old.isAuthenticated
    , remoteUrl = old.remoteUrl
    }


migrate_Types_AdminRoute : Evergreen.V4.Types.AdminRoute -> Evergreen.V12.Types.AdminRoute
migrate_Types_AdminRoute old =
    case old of
        Evergreen.V4.Types.AdminDefault ->
            Evergreen.V12.Types.AdminDefault

        Evergreen.V4.Types.AdminLogs p0 ->
            Evergreen.V12.Types.AdminLogs (p0 |> migrate_Types_AdminLogsUrlParams)

        Evergreen.V4.Types.AdminFetchModel ->
            Evergreen.V12.Types.AdminFetchModel


migrate_Types_DashboardColumn : Evergreen.V4.Types.DashboardColumn -> Evergreen.V12.Types.DashboardColumn
migrate_Types_DashboardColumn old =
    case old of
        Evergreen.V4.Types.ColCreatedAt ->
            Evergreen.V12.Types.ColCreatedAt

        Evergreen.V4.Types.ColDestinationUrl ->
            Evergreen.V12.Types.ColDestinationUrl

        Evergreen.V4.Types.ColSource ->
            Evergreen.V12.Types.ColSource

        Evergreen.V4.Types.ColMedium ->
            Evergreen.V12.Types.ColMedium

        Evergreen.V4.Types.ColCampaign ->
            Evergreen.V12.Types.ColCampaign

        Evergreen.V4.Types.ColShortUrl ->
            Evergreen.V12.Types.ColShortUrl

        Evergreen.V4.Types.ColTags ->
            Evergreen.V12.Types.ColTags


migrate_Types_EmailPasswordFormModel : Evergreen.V4.Types.EmailPasswordFormModel -> Evergreen.V12.Types.EmailPasswordFormModel
migrate_Types_EmailPasswordFormModel old =
    old


migrate_Types_LoginState : Evergreen.V4.Types.LoginState -> Evergreen.V12.Types.LoginState
migrate_Types_LoginState old =
    case old of
        Evergreen.V4.Types.JustArrived ->
            Evergreen.V12.Types.JustArrived

        Evergreen.V4.Types.NotLogged p0 ->
            Evergreen.V12.Types.NotLogged p0

        Evergreen.V4.Types.LoginTokenSent ->
            Evergreen.V12.Types.LoginTokenSent

        Evergreen.V4.Types.LoggedIn p0 ->
            Evergreen.V12.Types.LoggedIn (p0 |> migrate_Auth_Common_UserInfo)


migrate_Types_Preferences : Evergreen.V4.Types.Preferences -> Evergreen.V12.Types.Preferences
migrate_Types_Preferences old =
    old


migrate_Types_Route : Evergreen.V4.Types.Route -> Evergreen.V12.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V4.Types.Default ->
            Evergreen.V12.Types.Default

        Evergreen.V4.Types.Dashboard ->
            Evergreen.V12.Types.Dashboard

        Evergreen.V4.Types.Admin p0 ->
            Evergreen.V12.Types.Admin (p0 |> migrate_Types_AdminRoute)

        Evergreen.V4.Types.NotFound ->
            Evergreen.V12.Types.NotFound


migrate_Types_SortDirection : Evergreen.V4.Types.SortDirection -> Evergreen.V12.Types.SortDirection
migrate_Types_SortDirection old =
    case old of
        Evergreen.V4.Types.Ascending ->
            Evergreen.V12.Types.Ascending

        Evergreen.V4.Types.Descending ->
            Evergreen.V12.Types.Descending
