module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V1.Auth.Common
import Evergreen.V1.Logger
import Evergreen.V1.OAuth
import Evergreen.V1.OAuth.AuthorizationCode
import Evergreen.V1.Types
import Evergreen.V4.Auth.Common
import Evergreen.V4.Logger
import Evergreen.V4.OAuth
import Evergreen.V4.OAuth.AuthorizationCode
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Set


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V4.Types.BackendModel
migrate_Types_BackendModel old =
    { logState = old.logState |> migrate_Logger_LogState
    , pendingAuths = old.pendingAuths
    , sessions = old.sessions
    , users = old.users |> Dict.map (\k -> migrate_Types_User)
    , emailPasswordCredentials = old.emailPasswordCredentials
    , pollingJobs = old.pollingJobs |> Dict.map (\k -> migrate_Types_PollingStatus identity)
    }


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V4.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentRoute = old.currentRoute |> migrate_Types_Route
    , adminPage = old.adminPage |> migrate_Types_AdminPageModel
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    , login = old.login |> migrate_Types_LoginState
    , currentUser = old.currentUser |> Maybe.map migrate_Types_UserFrontend
    , pendingAuth = old.pendingAuth
    , preferences = old.preferences |> migrate_Types_Preferences
    , emailPasswordForm = old.emailPasswordForm |> migrate_Types_EmailPasswordFormModel
    , profileDropdownOpen = old.profileDropdownOpen
    , loginModalOpen = old.loginModalOpen
    , clients = old.clients |> List.map migrate_Types_BitlyClient
    , selectedClientId = old.selectedClientId
    , destinationUrl = old.destinationUrl
    , utmSource = old.utmSource
    , utmMedium = old.utmMedium
    , utmCampaign = old.utmCampaign
    , utmTerm = old.utmTerm
    , utmContent = old.utmContent
    , shortenResult = old.shortenResult
    , isShortening = old.isShortening
    , newClientName = old.newClientName
    , newClientApiKey = old.newClientApiKey
    , clientFormError = old.clientFormError
    , showClientManager = old.showClientManager
    , newSourceInput = ""
    , newTagInput = ""
    , editingClientId = Nothing
    , selectedSources = Set.empty
    , selectedTags = Set.empty
    , linksForDashboard = []
    , dashboardSortColumn = Evergreen.V4.Types.ColCreatedAt
    , dashboardSortDirection = Evergreen.V4.Types.Descending
    , dashboardFilters = Dict.empty
    }


migrate_Auth_Common_AuthChallengeReason : Evergreen.V1.Auth.Common.AuthChallengeReason -> Evergreen.V4.Auth.Common.AuthChallengeReason
migrate_Auth_Common_AuthChallengeReason old =
    case old of
        Evergreen.V1.Auth.Common.AuthSessionMissing ->
            Evergreen.V4.Auth.Common.AuthSessionMissing

        Evergreen.V1.Auth.Common.AuthSessionInvalid ->
            Evergreen.V4.Auth.Common.AuthSessionInvalid

        Evergreen.V1.Auth.Common.AuthSessionExpired ->
            Evergreen.V4.Auth.Common.AuthSessionExpired

        Evergreen.V1.Auth.Common.AuthSessionLoggedOut ->
            Evergreen.V4.Auth.Common.AuthSessionLoggedOut


migrate_Auth_Common_BackendMsg : Evergreen.V1.Auth.Common.BackendMsg -> Evergreen.V4.Auth.Common.BackendMsg
migrate_Auth_Common_BackendMsg old =
    case old of
        Evergreen.V1.Auth.Common.AuthSigninInitiated_ p0 ->
            Evergreen.V4.Auth.Common.AuthSigninInitiated_ p0

        Evergreen.V1.Auth.Common.AuthSigninInitiatedDelayed_ p0 p1 ->
            Evergreen.V4.Auth.Common.AuthSigninInitiatedDelayed_ p0 (p1 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V1.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V4.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6

        Evergreen.V1.Auth.Common.AuthSuccess p0 p1 p2 p3 p4 ->
            Evergreen.V4.Auth.Common.AuthSuccess p0
                p1
                p2
                p3
                (p4 |> Result.mapError migrate_Auth_Common_Error >> Result.map (Tuple.mapBoth migrate_Auth_Common_UserInfo (Maybe.map migrate_Auth_Common_Token)))

        Evergreen.V1.Auth.Common.AuthRenewSession p0 p1 ->
            Evergreen.V4.Auth.Common.AuthRenewSession p0 p1

        Evergreen.V1.Auth.Common.AuthLogout p0 p1 ->
            Evergreen.V4.Auth.Common.AuthLogout p0 p1


migrate_Auth_Common_Error : Evergreen.V1.Auth.Common.Error -> Evergreen.V4.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V1.Auth.Common.ErrStateMismatch ->
            Evergreen.V4.Auth.Common.ErrStateMismatch

        Evergreen.V1.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V4.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V1.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V4.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V1.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V4.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V1.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V4.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V1.Auth.Common.ErrAuthString p0 ->
            Evergreen.V4.Auth.Common.ErrAuthString p0


migrate_Auth_Common_Flow : Evergreen.V1.Auth.Common.Flow -> Evergreen.V4.Auth.Common.Flow
migrate_Auth_Common_Flow old =
    case old of
        Evergreen.V1.Auth.Common.Idle ->
            Evergreen.V4.Auth.Common.Idle

        Evergreen.V1.Auth.Common.Requested p0 ->
            Evergreen.V4.Auth.Common.Requested p0

        Evergreen.V1.Auth.Common.Pending ->
            Evergreen.V4.Auth.Common.Pending

        Evergreen.V1.Auth.Common.Authorized p0 p1 ->
            Evergreen.V4.Auth.Common.Authorized p0 p1

        Evergreen.V1.Auth.Common.Authenticated p0 ->
            Evergreen.V4.Auth.Common.Authenticated (p0 |> migrate_OAuth_Token)

        Evergreen.V1.Auth.Common.Done p0 ->
            Evergreen.V4.Auth.Common.Done (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V1.Auth.Common.Errored p0 ->
            Evergreen.V4.Auth.Common.Errored (p0 |> migrate_Auth_Common_Error)


migrate_Auth_Common_ToBackend : Evergreen.V1.Auth.Common.ToBackend -> Evergreen.V4.Auth.Common.ToBackend
migrate_Auth_Common_ToBackend old =
    case old of
        Evergreen.V1.Auth.Common.AuthSigninInitiated p0 ->
            Evergreen.V4.Auth.Common.AuthSigninInitiated p0

        Evergreen.V1.Auth.Common.AuthCallbackReceived p0 p1 p2 p3 ->
            Evergreen.V4.Auth.Common.AuthCallbackReceived p0 p1 p2 p3

        Evergreen.V1.Auth.Common.AuthRenewSessionRequested ->
            Evergreen.V4.Auth.Common.AuthRenewSessionRequested

        Evergreen.V1.Auth.Common.AuthLogoutRequested ->
            Evergreen.V4.Auth.Common.AuthLogoutRequested


migrate_Auth_Common_ToFrontend : Evergreen.V1.Auth.Common.ToFrontend -> Evergreen.V4.Auth.Common.ToFrontend
migrate_Auth_Common_ToFrontend old =
    case old of
        Evergreen.V1.Auth.Common.AuthInitiateSignin p0 ->
            Evergreen.V4.Auth.Common.AuthInitiateSignin p0

        Evergreen.V1.Auth.Common.AuthError p0 ->
            Evergreen.V4.Auth.Common.AuthError (p0 |> migrate_Auth_Common_Error)

        Evergreen.V1.Auth.Common.AuthSessionChallenge p0 ->
            Evergreen.V4.Auth.Common.AuthSessionChallenge (p0 |> migrate_Auth_Common_AuthChallengeReason)


migrate_Auth_Common_Token : Evergreen.V1.Auth.Common.Token -> Evergreen.V4.Auth.Common.Token
migrate_Auth_Common_Token old =
    { methodId = old.methodId
    , token = old.token |> migrate_OAuth_Token
    , created = old.created
    , expires = old.expires
    }


migrate_Auth_Common_UserInfo : Evergreen.V1.Auth.Common.UserInfo -> Evergreen.V4.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Logger_LogEntry : Evergreen.V1.Logger.LogEntry -> Evergreen.V4.Logger.LogEntry
migrate_Logger_LogEntry old =
    { index = old.index
    , timestamp = old.timestamp
    , level = old.level |> migrate_Logger_LogLevel
    , message = old.message
    }


migrate_Logger_LogLevel : Evergreen.V1.Logger.LogLevel -> Evergreen.V4.Logger.LogLevel
migrate_Logger_LogLevel old =
    case old of
        Evergreen.V1.Logger.Debug ->
            Evergreen.V4.Logger.Debug

        Evergreen.V1.Logger.Info ->
            Evergreen.V4.Logger.Info

        Evergreen.V1.Logger.Warn ->
            Evergreen.V4.Logger.Warn

        Evergreen.V1.Logger.Error ->
            Evergreen.V4.Logger.Error


migrate_Logger_LogState : Evergreen.V1.Logger.LogState -> Evergreen.V4.Logger.LogState
migrate_Logger_LogState old =
    { entries = old.entries |> List.map migrate_Logger_LogEntry
    , nextIndex = old.nextIndex
    , maxEntries = old.maxEntries
    }


migrate_Logger_Msg : Evergreen.V1.Logger.Msg -> Evergreen.V4.Logger.Msg
migrate_Logger_Msg old =
    case old of
        Evergreen.V1.Logger.GotTimestamp p0 p1 ->
            Evergreen.V4.Logger.GotTimestamp p0 p1


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V1.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V4.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V1.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V4.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V1.OAuth.ErrorCode -> Evergreen.V4.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V1.OAuth.InvalidRequest ->
            Evergreen.V4.OAuth.InvalidRequest

        Evergreen.V1.OAuth.UnauthorizedClient ->
            Evergreen.V4.OAuth.UnauthorizedClient

        Evergreen.V1.OAuth.AccessDenied ->
            Evergreen.V4.OAuth.AccessDenied

        Evergreen.V1.OAuth.UnsupportedResponseType ->
            Evergreen.V4.OAuth.UnsupportedResponseType

        Evergreen.V1.OAuth.InvalidScope ->
            Evergreen.V4.OAuth.InvalidScope

        Evergreen.V1.OAuth.ServerError ->
            Evergreen.V4.OAuth.ServerError

        Evergreen.V1.OAuth.TemporarilyUnavailable ->
            Evergreen.V4.OAuth.TemporarilyUnavailable

        Evergreen.V1.OAuth.Custom p0 ->
            Evergreen.V4.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V1.OAuth.Token -> Evergreen.V4.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V1.OAuth.Bearer p0 ->
            Evergreen.V4.OAuth.Bearer p0


migrate_Types_AdminLogsUrlParams : Evergreen.V1.Types.AdminLogsUrlParams -> Evergreen.V4.Types.AdminLogsUrlParams
migrate_Types_AdminLogsUrlParams old =
    old


migrate_Types_AdminPageModel : Evergreen.V1.Types.AdminPageModel -> Evergreen.V4.Types.AdminPageModel
migrate_Types_AdminPageModel old =
    { logs = old.logs |> List.map migrate_Logger_LogEntry
    , isAuthenticated = old.isAuthenticated
    , remoteUrl = old.remoteUrl
    }


migrate_Types_AdminRoute : Evergreen.V1.Types.AdminRoute -> Evergreen.V4.Types.AdminRoute
migrate_Types_AdminRoute old =
    case old of
        Evergreen.V1.Types.AdminDefault ->
            Evergreen.V4.Types.AdminDefault

        Evergreen.V1.Types.AdminLogs p0 ->
            Evergreen.V4.Types.AdminLogs (p0 |> migrate_Types_AdminLogsUrlParams)

        Evergreen.V1.Types.AdminFetchModel ->
            Evergreen.V4.Types.AdminFetchModel


migrate_Types_BackendMsg : Evergreen.V1.Types.BackendMsg -> Evergreen.V4.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V1.Types.NoOpBackendMsg ->
            Evergreen.V4.Types.NoOpBackendMsg

        Evergreen.V1.Types.GotLogTime p0 ->
            Evergreen.V4.Types.GotLogTime (p0 |> migrate_Logger_Msg)

        Evergreen.V1.Types.GotRemoteModel p0 ->
            Evergreen.V4.Types.GotRemoteModel (p0 |> Result.map migrate_Types_BackendModel)

        Evergreen.V1.Types.AuthBackendMsg p0 ->
            Evergreen.V4.Types.AuthBackendMsg (p0 |> migrate_Auth_Common_BackendMsg)

        Evergreen.V1.Types.EmailPasswordAuthResult p0 ->
            Evergreen.V4.Types.EmailPasswordAuthResult (p0 |> migrate_Types_EmailPasswordAuthResult)

        Evergreen.V1.Types.GotBitlyResponse p0 p1 p2 ->
            Evergreen.V4.Types.GotBitlyResponse p0 p1 p2


migrate_Types_BitlyClient : Evergreen.V1.Types.BitlyClient -> Evergreen.V4.Types.BitlyClient
migrate_Types_BitlyClient old =
    { id = old.id
    , name = old.name
    , apiKey = old.apiKey
    , sources = []
    , tags = []
    }


migrate_Types_EmailPasswordAuthMsg : Evergreen.V1.Types.EmailPasswordAuthMsg -> Evergreen.V4.Types.EmailPasswordAuthMsg
migrate_Types_EmailPasswordAuthMsg old =
    case old of
        Evergreen.V1.Types.EmailPasswordFormMsg p0 ->
            Evergreen.V4.Types.EmailPasswordFormMsg (p0 |> migrate_Types_EmailPasswordFormMsg)

        Evergreen.V1.Types.EmailPasswordLoginRequested p0 p1 ->
            Evergreen.V4.Types.EmailPasswordLoginRequested p0 p1

        Evergreen.V1.Types.EmailPasswordSignupRequested p0 p1 p2 ->
            Evergreen.V4.Types.EmailPasswordSignupRequested p0 p1 p2


migrate_Types_EmailPasswordAuthResult : Evergreen.V1.Types.EmailPasswordAuthResult -> Evergreen.V4.Types.EmailPasswordAuthResult
migrate_Types_EmailPasswordAuthResult old =
    case old of
        Evergreen.V1.Types.EmailPasswordSignupWithHash p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V4.Types.EmailPasswordSignupWithHash p0 p1 p2 p3 p4 p5 p6


migrate_Types_EmailPasswordAuthToBackend : Evergreen.V1.Types.EmailPasswordAuthToBackend -> Evergreen.V4.Types.EmailPasswordAuthToBackend
migrate_Types_EmailPasswordAuthToBackend old =
    case old of
        Evergreen.V1.Types.EmailPasswordLoginToBackend p0 p1 ->
            Evergreen.V4.Types.EmailPasswordLoginToBackend p0 p1

        Evergreen.V1.Types.EmailPasswordSignupToBackend p0 p1 p2 ->
            Evergreen.V4.Types.EmailPasswordSignupToBackend p0 p1 p2


migrate_Types_EmailPasswordFormModel : Evergreen.V1.Types.EmailPasswordFormModel -> Evergreen.V4.Types.EmailPasswordFormModel
migrate_Types_EmailPasswordFormModel old =
    old


migrate_Types_EmailPasswordFormMsg : Evergreen.V1.Types.EmailPasswordFormMsg -> Evergreen.V4.Types.EmailPasswordFormMsg
migrate_Types_EmailPasswordFormMsg old =
    case old of
        Evergreen.V1.Types.EmailPasswordFormEmailChanged p0 ->
            Evergreen.V4.Types.EmailPasswordFormEmailChanged p0

        Evergreen.V1.Types.EmailPasswordFormPasswordChanged p0 ->
            Evergreen.V4.Types.EmailPasswordFormPasswordChanged p0

        Evergreen.V1.Types.EmailPasswordFormConfirmPasswordChanged p0 ->
            Evergreen.V4.Types.EmailPasswordFormConfirmPasswordChanged p0

        Evergreen.V1.Types.EmailPasswordFormNameChanged p0 ->
            Evergreen.V4.Types.EmailPasswordFormNameChanged p0

        Evergreen.V1.Types.EmailPasswordFormToggleMode ->
            Evergreen.V4.Types.EmailPasswordFormToggleMode

        Evergreen.V1.Types.EmailPasswordFormSubmit ->
            Evergreen.V4.Types.EmailPasswordFormSubmit


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V4.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V4.Types.UrlChanged p0

        Evergreen.V1.Types.UrlRequested p0 ->
            Evergreen.V4.Types.UrlRequested p0

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V4.Types.NoOpFrontendMsg

        Evergreen.V1.Types.DirectToBackend p0 ->
            Evergreen.V4.Types.DirectToBackend (p0 |> migrate_Types_ToBackend)

        Evergreen.V1.Types.Admin_RemoteUrlChanged p0 ->
            Evergreen.V4.Types.Admin_RemoteUrlChanged p0

        Evergreen.V1.Types.Admin_LogsNavigate p0 ->
            Evergreen.V4.Types.Admin_LogsNavigate (p0 |> migrate_Types_AdminLogsUrlParams)

        Evergreen.V1.Types.Auth0SigninRequested ->
            Evergreen.V4.Types.Auth0SigninRequested

        Evergreen.V1.Types.EmailPasswordAuthMsg p0 ->
            Evergreen.V4.Types.EmailPasswordAuthMsg (p0 |> migrate_Types_EmailPasswordAuthMsg)

        Evergreen.V1.Types.Logout ->
            Evergreen.V4.Types.Logout

        Evergreen.V1.Types.ToggleDarkMode ->
            Evergreen.V4.Types.ToggleDarkMode

        Evergreen.V1.Types.ToggleProfileDropdown ->
            Evergreen.V4.Types.ToggleProfileDropdown

        Evergreen.V1.Types.ToggleLoginModal ->
            Evergreen.V4.Types.ToggleLoginModal

        Evergreen.V1.Types.CloseLoginModal ->
            Evergreen.V4.Types.CloseLoginModal

        Evergreen.V1.Types.EmailPasswordAuthError p0 ->
            Evergreen.V4.Types.EmailPasswordAuthError p0

        Evergreen.V1.Types.CopyToClipboard p0 ->
            Evergreen.V4.Types.CopyToClipboard p0

        Evergreen.V1.Types.ClipboardResult p0 ->
            Evergreen.V4.Types.ClipboardResult p0

        Evergreen.V1.Types.SelectClient p0 ->
            Evergreen.V4.Types.SelectClient p0

        Evergreen.V1.Types.DestinationUrlChanged p0 ->
            Evergreen.V4.Types.DestinationUrlChanged p0

        Evergreen.V1.Types.UtmSourceChanged p0 ->
            Evergreen.V4.Types.UtmSourceChanged p0

        Evergreen.V1.Types.UtmMediumChanged p0 ->
            Evergreen.V4.Types.UtmMediumChanged p0

        Evergreen.V1.Types.UtmCampaignChanged p0 ->
            Evergreen.V4.Types.UtmCampaignChanged p0

        Evergreen.V1.Types.UtmTermChanged p0 ->
            Evergreen.V4.Types.UtmTermChanged p0

        Evergreen.V1.Types.UtmContentChanged p0 ->
            Evergreen.V4.Types.UtmContentChanged p0

        Evergreen.V1.Types.CreateShortLink ->
            Evergreen.V4.Types.CreateShortLink

        Evergreen.V1.Types.ClearForm ->
            Evergreen.V4.Types.ClearForm

        Evergreen.V1.Types.NewClientNameChanged p0 ->
            Evergreen.V4.Types.NewClientNameChanged p0

        Evergreen.V1.Types.NewClientApiKeyChanged p0 ->
            Evergreen.V4.Types.NewClientApiKeyChanged p0

        Evergreen.V1.Types.AddClient ->
            Evergreen.V4.Types.AddClient

        Evergreen.V1.Types.DeleteClient p0 ->
            Evergreen.V4.Types.DeleteClient p0

        Evergreen.V1.Types.ToggleClientManager ->
            Evergreen.V4.Types.ToggleClientManager


migrate_Types_LoginState : Evergreen.V1.Types.LoginState -> Evergreen.V4.Types.LoginState
migrate_Types_LoginState old =
    case old of
        Evergreen.V1.Types.JustArrived ->
            Evergreen.V4.Types.JustArrived

        Evergreen.V1.Types.NotLogged p0 ->
            Evergreen.V4.Types.NotLogged p0

        Evergreen.V1.Types.LoginTokenSent ->
            Evergreen.V4.Types.LoginTokenSent

        Evergreen.V1.Types.LoggedIn p0 ->
            Evergreen.V4.Types.LoggedIn (p0 |> migrate_Auth_Common_UserInfo)


migrate_Types_PollingStatus : (a_old -> a_new) -> Evergreen.V1.Types.PollingStatus a_old -> Evergreen.V4.Types.PollingStatus a_new
migrate_Types_PollingStatus migrate_a old =
    case old of
        Evergreen.V1.Types.Busy ->
            Evergreen.V4.Types.Busy

        Evergreen.V1.Types.BusyWithTime p0 ->
            Evergreen.V4.Types.BusyWithTime p0

        Evergreen.V1.Types.Ready p0 ->
            Evergreen.V4.Types.Ready (p0 |> Result.map migrate_a)


migrate_Types_Preferences : Evergreen.V1.Types.Preferences -> Evergreen.V4.Types.Preferences
migrate_Types_Preferences old =
    old


migrate_Types_Route : Evergreen.V1.Types.Route -> Evergreen.V4.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V1.Types.Default ->
            Evergreen.V4.Types.Default

        Evergreen.V1.Types.Admin p0 ->
            Evergreen.V4.Types.Admin (p0 |> migrate_Types_AdminRoute)

        Evergreen.V1.Types.NotFound ->
            Evergreen.V4.Types.NotFound


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V4.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.A p0 ->
            Evergreen.V4.Types.A p0

        Evergreen.V1.Types.Admin_ClearLogs ->
            Evergreen.V4.Types.Admin_ClearLogs

        Evergreen.V1.Types.Admin_FetchLogs p0 ->
            Evergreen.V4.Types.Admin_FetchLogs p0

        Evergreen.V1.Types.Admin_FetchRemoteModel p0 ->
            Evergreen.V4.Types.Admin_FetchRemoteModel p0

        Evergreen.V1.Types.AuthToBackend p0 ->
            Evergreen.V4.Types.AuthToBackend (p0 |> migrate_Auth_Common_ToBackend)

        Evergreen.V1.Types.EmailPasswordAuthToBackend p0 ->
            Evergreen.V4.Types.EmailPasswordAuthToBackend (p0 |> migrate_Types_EmailPasswordAuthToBackend)

        Evergreen.V1.Types.GetUserToBackend ->
            Evergreen.V4.Types.GetUserToBackend

        Evergreen.V1.Types.LoggedOut ->
            Evergreen.V4.Types.LoggedOut

        Evergreen.V1.Types.NoOpToBackend ->
            Evergreen.V4.Types.NoOpToBackend

        Evergreen.V1.Types.SetDarkModePreference p0 ->
            Evergreen.V4.Types.SetDarkModePreference p0

        Evergreen.V1.Types.AddClientToBackend p0 p1 ->
            Evergreen.V4.Types.AddClientToBackend p0 p1

        Evergreen.V1.Types.DeleteClientToBackend p0 ->
            Evergreen.V4.Types.DeleteClientToBackend p0

        Evergreen.V1.Types.ShortenUrlToBackend p0 p1 p2 ->
            Evergreen.V4.Types.ShortenUrlToBackend p0 p1 (p2 |> migrate_Types_UtmParams)


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V4.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.A0 p0 ->
            Evergreen.V4.Types.A0 p0

        Evergreen.V1.Types.Admin_Logs_ToFrontend p0 ->
            Evergreen.V4.Types.Admin_Logs_ToFrontend (p0 |> List.map migrate_Logger_LogEntry)

        Evergreen.V1.Types.AuthSuccess p0 ->
            Evergreen.V4.Types.AuthSuccess (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V1.Types.AuthToFrontend p0 ->
            Evergreen.V4.Types.AuthToFrontend (p0 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V1.Types.NoOpToFrontend ->
            Evergreen.V4.Types.NoOpToFrontend

        Evergreen.V1.Types.PermissionDenied p0 ->
            Evergreen.V4.Types.PermissionDenied (p0 |> migrate_Types_ToBackend)

        Evergreen.V1.Types.UserDataToFrontend p0 ->
            Evergreen.V4.Types.UserDataToFrontend (p0 |> migrate_Types_UserFrontend)

        Evergreen.V1.Types.UserInfoMsg p0 ->
            Evergreen.V4.Types.UserInfoMsg p0

        Evergreen.V1.Types.ClientsUpdated p0 ->
            Evergreen.V4.Types.ClientsUpdated (p0 |> List.map migrate_Types_BitlyClient)

        Evergreen.V1.Types.ShortenUrlResult p0 ->
            Evergreen.V4.Types.ShortenUrlResult p0


migrate_Types_User : Evergreen.V1.Types.User -> Evergreen.V4.Types.User
migrate_Types_User old =
    { email = old.email
    , name = old.name
    , preferences = old.preferences |> migrate_Types_Preferences
    , clients = old.clients |> List.map migrate_Types_BitlyClient
    , nextClientId = old.nextClientId
    , links = []
    , nextLinkId = 1
    }


migrate_Types_UserFrontend : Evergreen.V1.Types.UserFrontend -> Evergreen.V4.Types.UserFrontend
migrate_Types_UserFrontend old =
    { email = old.email
    , isSysAdmin = old.isSysAdmin
    , role = old.role
    , preferences = old.preferences |> migrate_Types_Preferences
    , clients = old.clients |> List.map migrate_Types_BitlyClient
    , links = []
    }


migrate_Types_UtmParams : Evergreen.V1.Types.UtmParams -> Evergreen.V4.Types.UtmParams
migrate_Types_UtmParams old =
    old
